//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EATApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentsession
    {
        public System.TimeSpan SignIn { get; set; }
        public Nullable<System.TimeSpan> SignOut { get; set; }
        public int session_sessionID { get; set; }
        public string student_StudentID { get; set; }
    
        public virtual session session { get; set; }
        public virtual student student { get; set; }
    }
}
